### ISSUE TITLE
[Crash - Incompatibility] Ranged Weapon API seems to be incompatible with UnionLib (using Sinytra Connector)

### ISSUE THREAD

**Issue by ShinryuAspect** [FabricExtras/RangedWeaponAPI#6]
This is something I've been pinpointing over the past few days until I've found the culprit. It seems to throw a "java.lang.IllegalArgumentException: Can't find attribute ranged_weapon:haste" whenever I tried to open my inventory or shoot an arrow (doesn't matter if it was from vanilla weapons or Archers' ones). It seems I had UnionLib as a remnant of a mod I removed or updated and it was no longer needed and it was left there.
Just a quick note: I didn't try this in full isolation (just by leaving the API and the culprit alone), I simply readded it to the mod and checked that it was indeed causing the crash if it was present. If it is needed or you want me to, I can try them in bareminimum isolation to see if the problem it's just because UnionLib or if it was a compilation of mods I may be using.
I'm attaching also the crashlog just in case it's somehow useful to check how and why this happened.

[crash-2024-07-15_15.30.00-server.txt](https://github.com/user-attachments/files/16255381/crash-2024-07-15_15.30.00-server.txt)

EDIT: this is probably on Sinytra's end, as they told me (I also opened an issue on their end as I was instructed) but I'm leaving this issue here just in case it's worth looking into it.

**Comment by ZsoltMolnarrr** [comment]
I perform the attribute registration the most adequate way possible.

Hence I do not see any actionable point on my end. :(

Feel free to reopen in case a specific technical recommendation is known

**Comment by Lemonmito** [comment]
I encountered the same crash issue, which seems incompatible with union lib
[crash-2024-08-11_22.01.15-client.txt](https://github.com/user-attachments/files/16573909/crash-2024-08-11_22.01.15-client.txt)
